Added tests
mhorianin/book-store-web pull request #13
Opened 2024-04-12 13:12 UTC by mhorianin

2024-04-15 17:56 UTC, okuzan requested changes

2024-04-15 17:56 UTC, okuzan commented on src/test/resources/database/remove-saved-category-from-db.sql
> +DELETE FROM categories WHERE name = 'Verse';
i'd suggest forming a habit and always reviewing your PR to fix no empty line at EOF issues
![image](https://github.com/mhorianin/book-store-web/assets/49767049/65a29244-4a57-4fe7-b966-b850c84d1d2f)

2024-04-15 17:56 UTC, okuzan commented on src/test/java/com/example/bookstoreweb/repository/BookRepositoryTest.java
> +    void findAllByCategoryId_ValidId_ReturnOneBook() {
some of your test methods are public, some are not, better unify this

2024-04-15 17:56 UTC, okuzan commented on src/test/java/com/example/bookstoreweb/repository/BookRepositoryTest.java
> +            executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD)
common to both of these tests, extract

2024-04-15 17:56 UTC, okuzan commented on src/test/java/com/example/bookstoreweb/controller/CategoryControllerTest.java
> +        MvcResult result = mockMvc.perform(get("/api/categories"))
it's a good idea to extract base url to a constant, so you only ever have to change it in one place, if needed

2024-04-15 18:53 UTC, okuzan requested changes

2024-04-15 18:53 UTC, okuzan commented on src/test/java/com/example/bookstoreweb/repository/BookRepositoryTest.java
> +    void findAllByCategoryId_ValidId_ReturnOneBook() {
![image](https://github.com/mhorianin/book-store-web/assets/49767049/d1aacb66-5316-4e64-8251-08121b7da60e)
sorry for not being clear enough, I meant extract to a class level

2024-04-16 08:47 UTC, Rommelua approved these changes

2024-04-17 11:44 UTC, merged