test
mhorianin/book-store-web pull request #7
Opened 2024-03-14 13:42 UTC by mhorianin

2024-03-15 19:18 UTC, okuzan requested changes

2024-03-15 19:18 UTC, okuzan commented on src/main/java/com/example/bookstoreweb/model/User.java
>  @Table(name = "users")
user should implement soft delete

2024-03-15 19:18 UTC, okuzan commented on src/main/java/com/example/bookstoreweb/model/User.java
> +        return true;
should depend on if it's deleted

2024-03-15 19:18 UTC, okuzan commented on src/main/resources/db/changelog/changes/03-create-roles-table.yaml
> +                    nullable: false
add empty line

2024-03-15 19:18 UTC, okuzan commented on src/main/resources/db/changelog/changes/09-set-bcrypt-password.yaml
> +              - column: {name: password, value: '$2a$10$zarKKAjobZ6jX51HiSBl7eNFX4BeZ9Ch7EqulRX9TK/4Soxz5NntW'}
add comment with password in plaintext

2024-03-16 17:26 UTC, olekskov approved these changes

2024-03-16 17:26 UTC, olekskov commented on src/main/java/com/example/bookstoreweb/controller/BookController.java
> +    @PreAuthorize("hasAuthority('USER')")
Are you sure admin shouldn't have ability to get books?

2024-03-18 12:56 UTC, merged